# Generated by Django 5.0.2 on 2024-02-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full Time'), ('HT', 'Half Time')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
